# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',), 'verbose_name': '\u0422\u0432\u043e\u0440\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0422\u0432\u043e\u0440\u0435\u043d\u0438\u044f'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to=b''),
        ),
    ]
